### ISSUE TITLE
Guzzly TypeError on invoice send

### ISSUE THREAD

**Issue by theemstra** [0100Dev/WHMCS-Mollie-Payments#62]
Probably/possibly related to #47 

On invoice send (invoice cron run or manual invoice creation invocation we get a GuzzleHttp error.
We run PHP 7.4.

Due to this issue the invoicing isn't working correctly, it's only invoicing half of the invoicelines and breaks off, even when re-running the invoice cron or manually invoking invoice job it will not run the missed invoice lines. Which means this is (for us) a very urgent issue.

We use your free Mollie gateway and also have the paid Mollie Recurring gateway installed.

```
[Wed Apr 01 09:23:32.350959 2020] [proxy_fcgi:error] [pid 9248:tid 140374228006656] [client 141.101.105.93:29692] AH01071: Got error 'PHP message: [WHMCS Application] ERROR: TypeError: Argument 1 passed to GuzzleHttp\\Client::send() must be an instance of GuzzleHttp\\Message\\RequestInterface, instance of GuzzleHttp\\Psr7\\Request given, called in /var/www/virtual/whmcs/htdocs/modules/gateways/mollie/vendor/mollie/mollie-api-php/src/MollieApiClient.php on line 447 and defined in /var/www/virtual/whmcs/htdocs/vendor/guzzlehttp/guzzle/src/Client.php:158 Stack trace: #0 /var/www/virtual/whmcs/htdocs/modules/gateways/mollie/vendor/mollie/mollie-api-php/src/MollieApiClient.php(447): GuzzleHttp\\Client->send(Object(GuzzleHttp\\Psr7\\Request), Array) #1 /var/www/virtual/whmcs/htdocs/modules/gateways/mollie/vendor/mollie/mollie-api-php/src/MollieApiClient.php(404): Mollie\\Api\\MollieApiClient->performHttpCallToFullUrl('GET', 'https://api.mol...', NULL) #2 /var/www/virtual/whmcs/htdocs/modules/gateways/mollie/vendor/mollie/mollie-api-php/src/Endpoints/EndpointAbstract.php(99): Mollie\\Api\\MollieApiClient->performHtt...\n', referer: https://whmcs/admin/index.php
```

**Comment by Wouter0100** [comment]
Fixed with WHMCS 8 together with WHMCS Mollie Payments version 3.0. Closing for now, but thanks for reporting! :rocket:
