### ISSUE TITLE
Installatie fout

### ISSUE THREAD

**Issue by deanvanwijnen** [0100Dev/WHMCS-Mollie-Payments#92]
Hallo,

Wij willen de plugin gebruiken maar lopen tegen een fout op. Zodra we naar admin/configgateways.php gaan krijgen we de volgende fout:
### Something went wrong and we couldn't process your request.
For additional assistance, please reference the [WHMCS TroubleShooting Guide »](https://docs.whmcs.com/Troubleshooting_Guide)

```
Error: Call to a member function load_function() on null in /var/www/whmcs/modules/gateways/callback.php:10
Stack trace:
#0 /var/www/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/Gateway.php(0): unknown()
#1 /var/www/whmcs/admin/configgateways.php(0): WHMCS\Module\Gateway->load()
#2 {main}
```

Heb je hier een oplossing voor?
Alvast bedankt!

Fyi. we hebben het bestand uit releases gehaald en hebben **niet** de source code gedownload, zoals aangegeven in de instructies.

Met vriendelijke groet,
Dean

**Comment by deanvanwijnen** [comment]
Hello,

Thanks for your response. The readme says the following: _Upload all the files from the src folder to the /modules/gateways folder in your WHMCS installation.___
But you say _The src directory from the release ZIP should be placed in the {WHMCS}/modules/gateways directory._

What should I do with src?

**Comment by deanvanwijnen** [comment]
Hello,

I solved the issue by reinstalling the module.
Thanks!
