### ISSUE TITLE
Problem with paying

### ISSUE THREAD

**Issue by FinnXDeezzz** [0100Dev/WHMCS-Mollie-Payments#96]
Hello!

I have a new problem. Evertyime I select the payment methode and click pay I receive the following error message:
`League\Flysystem\Exception: Impossible to create the root directory "/home/colornod/public_html/whmcs/downloads". mkdir(): open_basedir restriction in effect. File(/home/colornod) is not within the allowed path(s): (/home2/colornod/:/tmp:/var/tmp:/opt/alt/php74/usr/share/pear/:/dev/urandom:/usr/local/lib/php/:/usr/local/php74/lib/php/) in /home2/colornod/domains/colornode.nl/public_html/vendor/league/flysystem/src/Adapter/Local.php:112
Stack trace:
#0 /home2/colornod/domains/colornode.nl/public_html/vendor/league/flysystem/src/Adapter/Local.php(78): League\Flysystem\Adapter\Local->ensureDirectory('/home/colornod/...')
#1 /home2/colornod/domains/colornode.nl/public_html/vendor/whmcs/whmcs-foundation/lib/File/Provider/LocalStorageProvider.php(0): League\Flysystem\Adapter\Local->__construct('/home/colornod/...')
#2 /home2/colornod/domains/colornode.nl/public_html/vendor/whmcs/whmcs-foundation/lib/File/Configuration/FileAssetSetting.php(0): WHMCS\File\Provider\LocalStorageProvider->createFilesystemAdapterForAssetType('email_template_...', '')
#3 /home2/colornod/domains/colornode.nl/public_html/vendor/whmcs/whmcs-foundation/lib/File/Storage.php(0): WHMCS\File\Configuration\FileAssetSetting->createFilesystemAdapter('')
#4 /home2/colornod/domains/colornode.nl/public_html/vendor/whmcs/whmcs-foundation/lib/File/Storage.php(0): WHMCS\File\Storage->createFilesystem('email_template_...')
#5 /home2/colornod/domains/colornode.nl/public_html/vendor/illuminate/support/Facades/Facade.php(261): WHMCS\File\Storage->emailTemplateAttachments()
#6 /home2/colornod/domains/colornode.nl/public_html/vendor/whmcs/whmcs-foundation/lib/Mail/Message.php(0): Illuminate\Support\Facades\Facade::__callStatic('emailTemplateAt...', Array)
#7 /home2/colornod/domains/colornode.nl/public_html/vendor/whmcs/whmcs-foundation/lib/Mail/Emailer.php(0): WHMCS\Mail\Message::createFromTemplate(Object(WHMCS\Mail\Template))
#8 /home2/colornod/domains/colornode.nl/public_html/includes/functions.php(0): WHMCS\Mail\Emailer::factoryByTemplate(Object(WHMCS\Mail\Template), 18, Array)
#9 /home2/colornod/domains/colornode.nl/public_html/includes/orderfunctions.php(0): sendMessage('Invoice Created', 18)
#10 /home2/colornod/domains/colornode.nl/public_html/cart.php(0): calcCartTotals(Object(WHMCS\User\Client), true, false)
#11 {main}`
![image](https://user-images.githubusercontent.com/89047756/181358485-3f7bb0b4-44f9-45b3-9719-9588c8786055.png)

Does anyone know how to solve this issue?
Is it a problem in this plugin or is it a problem with WHMCS?
I hope someone can help!

WHMCS version: 8.3.2
PHP version: 7.4

**Comment by FinnXDeezzz** [comment]
Issue solved!
Changed the storage settings and now it to the right directory (home2 instead of home).
https://docs.whmcs.com/Storage_Settings
